/**
 * Type-safe IPC client for TinSu.
 *
 * Uses tauri-specta generated bindings (src/bindings.ts) to provide
 * fully typed command invocations.
 *
 * NOTE: rspc (oscartbeaumont/rspc) is incompatible with Tauri v2 at this
 * time (rspc 1.0.0-rc.5 requires tauri v1). We use tauri-specta from the
 * same specta-rs ecosystem as a compatible alternative. The @rspc/client and
 * @rspc/tauri npm packages are installed for future compatibility when rspc
 * adds Tauri v2 support.
 */

// Re-export generated commands for use across the app.
// The bindings.ts file is auto-generated by tauri-specta during cargo build.
export { commands } from '../bindings'
export type {
  GetTaskInput,
  CreateTaskInput,
  ListTasksInput,
  UpdateTaskStatusInput,
  ReorderTasksInput,
  DeleteTaskInput,
  ListEpicsInput,
  CreateEpicInput,
  UpdateEpicInput,
  DeleteEpicInput,
  Model,
  EpicModel,
  AppError,
  SprintModel,
  ListSprintsInput,
  CreateSprintInput,
  UpdateSprintInput,
  UpdateSprintStatusInput,
  DeleteSprintInput,
  ProjectModel,
  ListRecentProjectsInput,
  GetWeeklyVelocityInput,
  WeeklyVelocityData,
  WeekBucket,
  TaskSessionModel,
  AttachResult,
  CreateSessionInput,
  ScrollbackResult,
  ScrollbackMetadata,
  ActivityModel,
  BranchStatus,
  GitDiffResult,
  GitDiffFile,
  GitDiffHunk,
  GitDiffLine,
  GitDiffSummary,
  ChatSessionModel,
  ChatSessionPreview,
  ChatMessageModel,
  SshConnectionProfile,
  CreateSshConnectionInput,
  UpdateSshConnectionInput,
  TestSshConnectionInput,
  SshConnectionTestResult,
  DiscoveredProject,
  RemoteProjectProfile,
  DiscoverProjectsInput,
  SaveRemoteProjectInput,
} from '../bindings'
