// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getTask: (input: GetTaskInput) => typedError<Model, AppError>(__TAURI_INVOKE("get_task", { input })),
	createTask: (input: CreateTaskInput) => typedError<Model, AppError>(__TAURI_INVOKE("create_task", { input })),
	/**
	 *  Returns all tasks for a project, ordered by sort_order ASC.
	 *  If project_id is empty, returns all tasks (no project filter).
	 */
	listTasks: (input: ListTasksInput) => typedError<Model[], AppError>(__TAURI_INVOKE("list_tasks", { input })),
	updateTaskStatus: (input: UpdateTaskStatusInput) => typedError<Model, AppError>(__TAURI_INVOKE("update_task_status", { input })),
	/**
	 *  Reorders tasks within a column by setting their sort_order to the given index positions.
	 *  Uses a transaction for atomicity.
	 */
	reorderTasks: (input: ReorderTasksInput) => typedError<null, AppError>(__TAURI_INVOKE("reorder_tasks", { input })),
	deleteTask: (input: DeleteTaskInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_task", { input })),
	// Returns tasks completed per week for the last N weeks.
	getWeeklyVelocity: (input: GetWeeklyVelocityInput) => typedError<WeeklyVelocityData, AppError>(__TAURI_INVOKE("get_weekly_velocity", { input })),
	// Returns all epics for a project. If project_id is empty, returns all epics.
	listEpics: (input: ListEpicsInput) => typedError<EpicModel[], AppError>(__TAURI_INVOKE("list_epics", { input })),
	// Creates a new epic.
	createEpic: (input: CreateEpicInput) => typedError<EpicModel, AppError>(__TAURI_INVOKE("create_epic", { input })),
	// Updates an existing epic.
	updateEpic: (input: UpdateEpicInput) => typedError<EpicModel, AppError>(__TAURI_INVOKE("update_epic", { input })),
	// Deletes an epic by id.
	deleteEpic: (input: DeleteEpicInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_epic", { input })),
	/**
	 *  Returns all sprints for a project ordered by created_at ASC.
	 *  If project_id is empty, returns all sprints.
	 */
	listSprints: (input: ListSprintsInput) => typedError<SprintModel[], AppError>(__TAURI_INVOKE("list_sprints", { input })),
	// Creates a new sprint.
	createSprint: (input: CreateSprintInput) => typedError<SprintModel, AppError>(__TAURI_INVOKE("create_sprint", { input })),
	// Updates an existing sprint's details.
	updateSprint: (input: UpdateSprintInput) => typedError<SprintModel, AppError>(__TAURI_INVOKE("update_sprint", { input })),
	// Updates only the status of an existing sprint.
	updateSprintStatus: (input: UpdateSprintStatusInput) => typedError<SprintModel, AppError>(__TAURI_INVOKE("update_sprint_status", { input })),
	// Deletes a sprint by id.
	deleteSprint: (input: DeleteSprintInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_sprint", { input })),
	// Returns the first active sprint for a project, or None if not found.
	getActiveSprint: (input: ListSprintsInput) => typedError<{
	id: string,
	name: string,
	start_date: string | null,
	end_date: string | null,
	status: string,
	goal: string | null,
	velocity: number | null,
	capacity: number | null,
	project_id: string,
	story_prefix: string | null,
	epics_file_path: string | null,
	created_at: number,
} | null, AppError>(__TAURI_INVOKE("get_active_sprint", { input })),
	// Returns recent projects ordered by last_opened_at DESC, created_at DESC, capped at limit.
	listRecentProjects: (input: ListRecentProjectsInput) => typedError<ProjectModel[], AppError>(__TAURI_INVOKE("list_recent_projects", { input })),
	// Returns true if path is a directory containing .tinsu/config.yaml.
	validateProjectPath: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("validate_project_path", { path })),
	// Opens a project by path: reads config, upserts in DB, returns ProjectModel.
	openProjectByPath: (path: string) => typedError<ProjectModel, AppError>(__TAURI_INVOKE("open_project_by_path", { path })),
	// Removes a project from DB (does NOT delete files).
	removeProject: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_project", { id })),
	// Opens a native folder picker dialog; returns the selected ProjectModel or None if cancelled.
	openProjectDialog: () => typedError<{
	id: string,
	path: string,
	name: string,
	created_at: number,
	last_opened_at: number | null,
} | null, AppError>(__TAURI_INVOKE("open_project_dialog")),
	// Opens a native folder picker and returns the selected path or None if cancelled.
	selectParentDirectory: () => typedError<string | null, AppError>(__TAURI_INVOKE("select_parent_directory")),
	// Creates a new project directory, initializes git, writes config, and inserts in DB.
	createProject: (parentDir: string, projectName: string) => typedError<ProjectModel, AppError>(__TAURI_INVOKE("create_project", { parentDir, projectName })),
	// Checks required tools and returns their install status.
	verifyTools: (projectPath: string) => typedError<ToolCheckResult[], AppError>(__TAURI_INVOKE("verify_tools", { projectPath })),
	// Returns BMAD installation status by reading _bmad/_config/manifest.yaml.
	bmadCheckStatus: (projectPath: string) => typedError<BmadStatus, AppError>(__TAURI_INVOKE("bmad_check_status", { projectPath })),
	// Runs `npx bmad-method install` with the given options.
	bmadInstallToPath: (input: BmadInstallInput) => typedError<null, AppError>(__TAURI_INVOKE("bmad_install_to_path", { input })),
	// Attempts to install Node.js via the platform package manager.
	installNodejs: () => typedError<null, AppError>(__TAURI_INVOKE("install_nodejs")),
	/**
	 *  Create a tmux session for a task and upsert a `task_sessions` record.
	 *  If the task has a worktree_path, the session is created in that directory
	 *  so the agent operates in the isolated branch.
	 */
	createTaskSession: (input: CreateSessionInput) => typedError<TaskSessionModel, AppError>(__TAURI_INVOKE("create_task_session", { input })),
	// Attach a PTY process to an existing tmux session for a task.
	attachTaskTerminal: (taskId: string, cols: number | null, rows: number | null, onData: Channel<number[]>) => typedError<AttachResult, AppError>(__TAURI_INVOKE("attach_task_terminal", { taskId, cols, rows, onData })),
	// Detach PTY from tmux session (kills the PTY process, leaves tmux running).
	detachTaskTerminal: (processId: string) => typedError<null, AppError>(__TAURI_INVOKE("detach_task_terminal", { processId })),
	// Spawn a generic PTY process (for the terminal dock).
	spawnPty: (command: string | null, args: string[], cwd: string | null, cols: number | null, rows: number | null, onData: Channel<number[]>) => typedError<string, AppError>(__TAURI_INVOKE("spawn_pty", { command, args, cwd, cols, rows, onData })),
	// Write data to a PTY process.
	writePty: (processId: string, data: string) => typedError<null, AppError>(__TAURI_INVOKE("write_pty", { processId, data })),
	// Resize a PTY process.
	resizePty: (processId: string, cols: number, rows: number) => typedError<null, AppError>(__TAURI_INVOKE("resize_pty", { processId, cols, rows })),
	// Kill a generic PTY process. Exit event is emitted by the reader thread.
	killPty: (processId: string) => typedError<null, AppError>(__TAURI_INVOKE("kill_pty", { processId })),
	// Kill the tmux session for a task, remove DB record, kill any active PTY.
	killTaskSession: (taskId: string) => typedError<null, AppError>(__TAURI_INVOKE("kill_task_session", { taskId })),
	// Get the task session record from DB.
	getTaskSession: (taskId: string) => typedError<{
	id: string,
	task_id: string,
	session_id: string | null,
	tmux_session: string | null,
	current_phase: string | null,
	created_at: number,
} | null, AppError>(__TAURI_INVOKE("get_task_session", { taskId })),
	// Get scrollback backup for a task.
	getScrollbackBackup: (taskId: string) => typedError<ScrollbackResult, AppError>(__TAURI_INVOKE("get_scrollback_backup", { taskId })),
	// Save scrollback backup for a task.
	saveScrollbackBackup: (taskId: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("save_scrollback_backup", { taskId, content })),
	// Start a background session monitor for a task. Fire-and-forget.
	startSessionMonitor: (taskId: string) => typedError<null, AppError>(__TAURI_INVOKE("start_session_monitor", { taskId })),
	// Update session_id for a task when Claude Code CLI starts.
	registerSessionId: (taskId: string, sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("register_session_id", { taskId, sessionId })),
	// Log an activity event for a task. Returns the created ActivityModel.
	logActivity: (taskId: string, eventType: string, payload: string | null) => typedError<ActivityModel, AppError>(__TAURI_INVOKE("log_activity", { taskId, eventType, payload })),
	// List activities for a task with optional filtering and pagination.
	listActivitiesForTask: (taskId: string, limit: number | null, offset: number | null, eventTypes: string[] | null) => typedError<ActivityModel[], AppError>(__TAURI_INVOKE("list_activities_for_task", { taskId, limit, offset, eventTypes })),
	/**
	 *  Returns the git diff for the task's worktree vs main.
	 *  Returns an empty diff if the task has no worktree or is already merged.
	 */
	getTaskDiff: (taskId: string) => typedError<GitDiffResult, AppError>(__TAURI_INVOKE("get_task_diff", { taskId })),
	/**
	 *  Returns branch status (commits ahead/behind main, uncommitted changes) for a task's branch.
	 *  Returns zeroed status if the task has no branch.
	 */
	getBranchStatus: (taskId: string) => typedError<BranchStatus, AppError>(__TAURI_INVOKE("get_branch_status", { taskId })),
	/**
	 *  Approve a task: detect conflicts, merge branch into main, update task to done.
	 * 
	 *  On conflict: sets `has_merge_conflict=1`, `conflict_files=JSON`, returns `AppError::GitConflict`.
	 *  On success: merges, stores `merge_commit_sha`, removes worktree, sets status=done.
	 */
	approveTask: (taskId: string) => typedError<null, AppError>(__TAURI_INVOKE("approve_task", { taskId })),
	/**
	 *  Reject a task: store feedback, move status back to in_progress.
	 *  Does NOT modify the worktree — agent continues in the same branch.
	 */
	rejectTask: (taskId: string, feedback: string) => typedError<null, AppError>(__TAURI_INVOKE("reject_task", { taskId, feedback })),
	// Create a new chat session, spin up the tmux session, and return the session model.
	createChatSession: (projectId: string, agentPersona: string | null, workflowKey: string | null) => typedError<ChatSessionModel, AppError>(__TAURI_INVOKE("create_chat_session", { projectId, agentPersona, workflowKey })),
	// List all chat sessions for a project with last message preview, sorted by activity.
	listChatSessionsWithPreview: (projectId: string) => typedError<ChatSessionPreview[], AppError>(__TAURI_INVOKE("list_chat_sessions_with_preview", { projectId })),
	// Get messages for a chat session, sorted by created_at ASC.
	getChatMessages: (sessionId: string, limit: number | null, offset: number | null) => typedError<ChatMessageModel[], AppError>(__TAURI_INVOKE("get_chat_messages", { sessionId, limit, offset })),
	// Send a message to the active chat session's tmux session.
	sendChatMessage: (sessionId: string, content: string) => typedError<ChatMessageModel, AppError>(__TAURI_INVOKE("send_chat_message", { sessionId, content })),
	// Update a chat session's status.
	updateSessionStatus: (sessionId: string, status: string) => typedError<null, AppError>(__TAURI_INVOKE("update_session_status", { sessionId, status })),
	// Delete a chat session (kills tmux session, cascades messages).
	deleteChatSession: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_chat_session", { sessionId })),
	// Delete a single chat message.
	deleteChatMessage: (messageId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_chat_message", { messageId })),
	// Clear all messages for a session and reset last_message_at.
	clearSessionMessages: (sessionId: string) => typedError<null, AppError>(__TAURI_INVOKE("clear_session_messages", { sessionId })),
	// Update the skip_permissions flag for a session.
	updateSkipPermissions: (sessionId: string, skipPermissions: boolean) => typedError<null, AppError>(__TAURI_INVOKE("update_skip_permissions", { sessionId, skipPermissions })),
	// Get a chat session by its workflow key.
	getChatSessionByWorkflowKey: (projectId: string, workflowKey: string) => typedError<{
	id: string,
	session_uuid: string,
	agent_persona: string | null,
	workflow_phase: string | null,
	project_id: string,
	status: string,
	created_at: number,
	updated_at: number,
	last_message_at: number | null,
	workflow_key: string | null,
	skip_permissions: number,
	tmux_session: string | null,
} | null, AppError>(__TAURI_INVOKE("get_chat_session_by_workflow_key", { projectId, workflowKey })),
	// Attach a PTY to the chat session's tmux session (mirrors attach_task_terminal).
	attachChatTerminal: (sessionId: string, cols: number | null, rows: number | null, onData: Channel<number[]>) => typedError<AttachResult, AppError>(__TAURI_INVOKE("attach_chat_terminal", { sessionId, cols, rows, onData })),
	// Detach a PTY from a chat session (leaves tmux running).
	detachChatTerminal: (processId: string) => typedError<null, AppError>(__TAURI_INVOKE("detach_chat_terminal", { processId })),
	// Scan all known BMAD planning artifacts for a project.
	scanArtifacts: (projectId: string) => typedError<ArtifactScanResult[], AppError>(__TAURI_INVOKE("scan_artifacts", { projectId })),
	// Get the markdown content of an artifact.
	getArtifactContent: (projectId: string, workflowKey: string) => typedError<ArtifactContentResult, AppError>(__TAURI_INVOKE("get_artifact_content", { projectId, workflowKey })),
	// Update the stored status for an artifact.
	updateArtifactStatus: (projectId: string, artifactKey: string, status: string) => typedError<null, AppError>(__TAURI_INVOKE("update_artifact_status", { projectId, artifactKey, status })),
	// Create a new workflow run record.
	createWorkflowRun: (projectId: string, workflowKey: string, phase: string | null, agentName: string | null, taskId: string | null, inputArtifacts: string[] | null) => typedError<WorkflowRunModel, AppError>(__TAURI_INVOKE("create_workflow_run", { projectId, workflowKey, phase, agentName, taskId, inputArtifacts })),
	// Update a workflow run's status (and optionally output artifacts).
	updateWorkflowRun: (runId: string, status: string, outputArtifacts: string[] | null) => typedError<WorkflowRunModel, AppError>(__TAURI_INVOKE("update_workflow_run", { runId, status, outputArtifacts })),
	// List workflow runs for a project (ordered by started_at DESC).
	listWorkflowRuns: (projectId: string, limit: number | null) => typedError<WorkflowRunModel[], AppError>(__TAURI_INVOKE("list_workflow_runs", { projectId, limit })),
	// Get the currently active workflow run for a project (status running or needs-input).
	getActiveWorkflowRun: (projectId: string) => typedError<{
	id: string,
	project_id: string,
	workflow_key: string,
	phase: string | null,
	status: string,
	started_at: number | null,
	finished_at: number | null,
	input_artifacts: string[] | null,
	output_artifacts: string[] | null,
	agent_name: string | null,
	task_id: string | null,
} | null, AppError>(__TAURI_INVOKE("get_active_workflow_run", { projectId })),
	// Parse a readiness report file and save as a gate_decision record.
	parseAndSaveGateResult: (projectId: string, workflowRunId: string | null) => typedError<GateDecisionModel, AppError>(__TAURI_INVOKE("parse_and_save_gate_result", { projectId, workflowRunId })),
	// Get the most recent gate decision for a project.
	getLatestGateDecision: (projectId: string) => typedError<{
	id: string,
	project_id: string,
	decision: string,
	rationale: string | null,
	issues: GateIssue[] | null,
	created_at: number,
	workflow_run_id: string | null,
} | null, AppError>(__TAURI_INVOKE("get_latest_gate_decision", { projectId })),
	// List gate decisions for a project (ordered by created_at DESC).
	listGateDecisions: (projectId: string, limit: number | null) => typedError<GateDecisionModel[], AppError>(__TAURI_INVOKE("list_gate_decisions", { projectId, limit })),
	// Approve all artifacts for implementation (requires latest gate decision = pass).
	approveForImplementation: (projectId: string) => typedError<number, AppError>(__TAURI_INVOKE("approve_for_implementation", { projectId })),
};

/* Types */
export type ActivityModel = {
	id: string,
	task_id: string,
	event_type: string,
	payload: string | null,
	created_at: number,
};

export type AppError = ({ NotFound: string }) & { BadRequest?: never; Database?: never; GitConflict?: never; GitOperation?: never; Internal?: never } | ({ BadRequest: string }) & { Database?: never; GitConflict?: never; GitOperation?: never; Internal?: never; NotFound?: never } | ({ Internal: string }) & { BadRequest?: never; Database?: never; GitConflict?: never; GitOperation?: never; NotFound?: never } | ({ Database: string }) & { BadRequest?: never; GitConflict?: never; GitOperation?: never; Internal?: never; NotFound?: never } | ({ GitConflict: string }) & { BadRequest?: never; Database?: never; GitOperation?: never; Internal?: never; NotFound?: never } | ({ GitOperation: string }) & { BadRequest?: never; Database?: never; GitConflict?: never; Internal?: never; NotFound?: never };

export type ArtifactContentResult = {
	content: string,
	file_path: string,
	last_modified: number,
	size_bytes: number,
	word_count: number,
	workflow_key: string,
};

export type ArtifactScanResult = {
	workflow_key: string,
	exists: boolean,
	filename: string | null,
	last_modified: number | null,
	size_bytes: number | null,
	status: string,
};

export type AttachResult = {
	process_id: string,
	attached: boolean,
};

export type BmadInstallInput = {
	project_path: string,
	modules: string[],
	tools: string[],
	user_name: string,
	communication_language: string,
	document_output_language: string,
};

export type BmadStatus = {
	installed: boolean,
	version: string | null,
	modules: string[] | null,
};

export type BranchStatus = {
	commitsAhead: number,
	commitsBehind: number,
	hasUncommittedChanges: boolean,
};

export type ChatMessageModel = {
	id: string,
	session_id: string,
	role: string,
	content: string,
	tool_name: string | null,
	tool_input: string | null,
	created_at: number,
};

export type ChatSessionModel = {
	id: string,
	session_uuid: string,
	agent_persona: string | null,
	workflow_phase: string | null,
	project_id: string,
	status: string,
	created_at: number,
	updated_at: number,
	last_message_at: number | null,
	workflow_key: string | null,
	skip_permissions: number,
	tmux_session: string | null,
};

// Flattened session preview — all session fields + last_message_preview.
export type ChatSessionPreview = {
	id: string,
	session_uuid: string,
	agent_persona: string | null,
	workflow_phase: string | null,
	project_id: string,
	status: string,
	created_at: number,
	updated_at: number,
	last_message_at: number | null,
	workflow_key: string | null,
	skip_permissions: number,
	tmux_session: string | null,
	last_message_preview: string | null,
};

export type CreateEpicInput = {
	title: string,
	description: string | null,
	color: string | null,
	epic_number: number | null,
	goal: string | null,
	sprint_id: string | null,
	project_id: string,
};

export type CreateSessionInput = {
	task_id: string,
	project_path: string,
};

export type CreateSprintInput = {
	name: string,
	goal: string | null,
	status: string,
	start_date: string | null,
	end_date: string | null,
	project_id: string,
};

export type CreateTaskInput = {
	title: string,
	project_id: string,
};

export type DeleteEpicInput = {
	id: string,
};

export type DeleteSprintInput = {
	id: string,
};

export type DeleteTaskInput = {
	id: string,
};

/**
 *  DTO for epic data exposed via tauri-specta.
 *  Mirrors epic::Model but with a unique specta type name to avoid collision with task::Model.
 */
export type EpicModel = {
	id: string,
	title: string,
	description: string | null,
	color: string | null,
	epic_number: number | null,
	goal: string | null,
	sprint_id: string | null,
	project_id: string,
	created_at: number,
};

export type GateDecisionModel = {
	id: string,
	project_id: string,
	decision: string,
	rationale: string | null,
	issues: GateIssue[] | null,
	created_at: number,
	workflow_run_id: string | null,
};

export type GateIssue = {
	severity: string,
	description: string,
	artifact_key: string | null,
	section_ref: string | null,
};

export type GetTaskInput = {
	id: string,
};

export type GetWeeklyVelocityInput = {
	weeks: number,
	project_id: string,
};

export type GitDiffFile = {
	path: string,
	oldPath: string | null,
	status: string,
	isBinary: boolean | null,
	additions: number,
	deletions: number,
	hunks: GitDiffHunk[],
};

export type GitDiffHunk = {
	header: string,
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	lines: GitDiffLine[],
};

export type GitDiffLine = {
	type: string,
	content: string,
	oldLineNo: number | null,
	newLineNo: number | null,
};

export type GitDiffResult = {
	files: GitDiffFile[],
	summary: GitDiffSummary,
};

export type GitDiffSummary = {
	filesChanged: number,
	linesAdded: number,
	linesRemoved: number,
};

export type ListEpicsInput = {
	project_id: string,
};

export type ListRecentProjectsInput = {
	limit: number,
};

export type ListSprintsInput = {
	project_id: string,
};

export type ListTasksInput = {
	project_id: string,
};

export type Model = {
	id: string,
	title: string,
	description: string | null,
	status: string,
	sort_order: number,
	epic_id: string | null,
	sprint_id: string | null,
	task_type: string,
	phase_number: number | null,
	phase_name: string | null,
	bmad_agent: string | null,
	bmad_workflow: string | null,
	is_start_here: number,
	artifact_path: string | null,
	story_number: string | null,
	story_file_path: string | null,
	full_content: string | null,
	story_file_status: string | null,
	context_notes: string | null,
	project_id: string,
	worktree_path: string | null,
	branch_name: string | null,
	merge_commit_sha: string | null,
	has_merge_conflict: number,
	conflict_files: string | null,
	worktree_skipped: number,
	rejection_feedback: string | null,
	rejected_agent_run_id: string | null,
	inline_comments: string | null,
	rejection_count: number,
	last_review_commit: string | null,
	created_at: number,
	updated_at: number,
};

// DTO for project data exposed via tauri-specta.
export type ProjectModel = {
	id: string,
	path: string,
	name: string,
	created_at: number,
	last_opened_at: number | null,
};

export type ReorderTasksInput = {
	task_ids: string[],
	status: string,
};

export type ScrollbackMetadata = {
	last_backup: number,
	size: number,
};

export type ScrollbackResult = {
	content: string | null,
	metadata: ScrollbackMetadata | null,
};

/**
 *  DTO for sprint data exposed via tauri-specta.
 *  Mirrors sprint::Model but with a unique specta type name to avoid collision.
 */
export type SprintModel = {
	id: string,
	name: string,
	start_date: string | null,
	end_date: string | null,
	status: string,
	goal: string | null,
	velocity: number | null,
	capacity: number | null,
	project_id: string,
	story_prefix: string | null,
	epics_file_path: string | null,
	created_at: number,
};

export type TaskSessionModel = {
	id: string,
	task_id: string,
	session_id: string | null,
	tmux_session: string | null,
	current_phase: string | null,
	created_at: number,
};

export type ToolCheckResult = {
	id: string,
	name: string,
	// "installed" | "missing" | "error"
	status: string,
	version: string | null,
	critical: boolean,
	install_hint: string | null,
};

export type UpdateEpicInput = {
	id: string,
	title: string,
	description: string | null,
	color: string | null,
	goal: string | null,
	sprint_id: string | null,
};

export type UpdateSprintInput = {
	id: string,
	name: string,
	goal: string | null,
	start_date: string | null,
	end_date: string | null,
};

export type UpdateSprintStatusInput = {
	id: string,
	status: string,
};

export type UpdateTaskStatusInput = {
	id: string,
	status: string,
};

export type WeekBucket = {
	week_label: string,
	count: number,
};

export type WeeklyVelocityData = {
	total_completed: number,
	weeks: WeekBucket[],
};

export type WorkflowRunModel = {
	id: string,
	project_id: string,
	workflow_key: string,
	phase: string | null,
	status: string,
	started_at: number | null,
	finished_at: number | null,
	input_artifacts: string[] | null,
	output_artifacts: string[] | null,
	agent_name: string | null,
	task_id: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

