// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getTask: (input: GetTaskInput) => typedError<Model, AppError>(__TAURI_INVOKE("get_task", { input })),
	createTask: (input: CreateTaskInput) => typedError<Model, AppError>(__TAURI_INVOKE("create_task", { input })),
	/**
	 *  Returns all tasks for a project, ordered by sort_order ASC.
	 *  If project_id is empty, returns all tasks (no project filter).
	 */
	listTasks: (input: ListTasksInput) => typedError<Model[], AppError>(__TAURI_INVOKE("list_tasks", { input })),
	updateTaskStatus: (input: UpdateTaskStatusInput) => typedError<Model, AppError>(__TAURI_INVOKE("update_task_status", { input })),
	/**
	 *  Reorders tasks within a column by setting their sort_order to the given index positions.
	 *  Uses a transaction for atomicity.
	 */
	reorderTasks: (input: ReorderTasksInput) => typedError<null, AppError>(__TAURI_INVOKE("reorder_tasks", { input })),
	deleteTask: (input: DeleteTaskInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_task", { input })),
	// Returns all epics for a project. If project_id is empty, returns all epics.
	listEpics: (input: ListEpicsInput) => typedError<EpicModel[], AppError>(__TAURI_INVOKE("list_epics", { input })),
};

/* Types */
export type AppError = ({ NotFound: string }) & { BadRequest?: never; Database?: never; Internal?: never } | ({ BadRequest: string }) & { Database?: never; Internal?: never; NotFound?: never } | ({ Internal: string }) & { BadRequest?: never; Database?: never; NotFound?: never } | ({ Database: string }) & { BadRequest?: never; Internal?: never; NotFound?: never };

export type CreateTaskInput = {
	title: string,
	project_id: string,
};

export type DeleteTaskInput = {
	id: string,
};

/**
 *  DTO for epic data exposed via tauri-specta.
 *  Mirrors epic::Model but with a unique specta type name to avoid collision with task::Model.
 */
export type EpicModel = {
	id: string,
	title: string,
	description: string | null,
	color: string | null,
	epic_number: number | null,
	goal: string | null,
	sprint_id: string | null,
	project_id: string,
	created_at: number,
};

export type GetTaskInput = {
	id: string,
};

export type ListEpicsInput = {
	project_id: string,
};

export type ListTasksInput = {
	project_id: string,
};

export type Model = {
	id: string,
	title: string,
	description: string | null,
	status: string,
	sort_order: number,
	epic_id: string | null,
	sprint_id: string | null,
	task_type: string,
	phase_number: number | null,
	phase_name: string | null,
	bmad_agent: string | null,
	bmad_workflow: string | null,
	is_start_here: number,
	artifact_path: string | null,
	story_number: string | null,
	story_file_path: string | null,
	full_content: string | null,
	story_file_status: string | null,
	context_notes: string | null,
	project_id: string,
	worktree_path: string | null,
	branch_name: string | null,
	merge_commit_sha: string | null,
	has_merge_conflict: number,
	conflict_files: string | null,
	worktree_skipped: number,
	rejection_feedback: string | null,
	rejected_agent_run_id: string | null,
	inline_comments: string | null,
	rejection_count: number,
	last_review_commit: string | null,
	created_at: number,
	updated_at: number,
};

export type ReorderTasksInput = {
	task_ids: string[],
	status: string,
};

export type UpdateTaskStatusInput = {
	id: string,
	status: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

